# kubernetes/postgres-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  POSTGRES_USER: YmFja3N0YWdl
  POSTGRES_PASSWORD: aHVudGVyMg==
  POSTGRES_SERVICE_PORT: NTQzMg==
